USE `spamsdb`;

ALTER TABLE `roles`
  ADD COLUMN IF NOT EXISTS `name` VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `description` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME NULL DEFAULT NULL;

UPDATE `roles`
SET `name` = `role_name`
WHERE (`name` IS NULL OR `name` = '')
  AND `role_name` IS NOT NULL;

ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `employee_id` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `office_id` INT(10) UNSIGNED DEFAULT NULL;

ALTER TABLE `departments`
  ADD COLUMN IF NOT EXISTS `description` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `created_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME NULL DEFAULT NULL;

ALTER TABLE `employees`
  ADD COLUMN IF NOT EXISTS `email` VARCHAR(150) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `department_id` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `responsibility_code_id` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `employment_status` VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `is_unit_head` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `created_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_by` INT(10) UNSIGNED DEFAULT NULL;

ALTER TABLE `offices`
  ADD COLUMN IF NOT EXISTS `office_head_employee_id` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `description` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `created_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_by` INT(10) UNSIGNED DEFAULT NULL;

UPDATE `offices`
SET `office_head_employee_id` = `head_employee_id`
WHERE `office_head_employee_id` IS NULL
  AND `head_employee_id` IS NOT NULL;

ALTER TABLE `responsibility_codes`
  ADD COLUMN IF NOT EXISTS `updated_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `created_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME NULL DEFAULT NULL;

ALTER TABLE `suppliers`
  ADD COLUMN IF NOT EXISTS `tin_no` VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `created_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_by` INT(10) UNSIGNED DEFAULT NULL;

UPDATE `suppliers`
SET `tin_no` = `tin`
WHERE (`tin_no` IS NULL OR `tin_no` = '')
  AND `tin` IS NOT NULL;

ALTER TABLE `funds`
  ADD COLUMN IF NOT EXISTS `description` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `created_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME NULL DEFAULT NULL;

ALTER TABLE `account_codes`
  ADD COLUMN IF NOT EXISTS `account_group` VARCHAR(50) NOT NULL DEFAULT 'asset',
  ADD COLUMN IF NOT EXISTS `description` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `created_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME NULL DEFAULT NULL;

ALTER TABLE `classifications`
  ADD COLUMN IF NOT EXISTS `description` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `created_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_by` INT(10) UNSIGNED DEFAULT NULL;

UPDATE `classifications`
SET `classification_code` = CONCAT('CLS-LEGACY-', LPAD(`id`, 4, '0'))
WHERE `classification_code` IS NULL
   OR `classification_code` = '';

ALTER TABLE `mode_of_procurements`
  ADD COLUMN IF NOT EXISTS `description` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `created_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME NULL DEFAULT NULL;

ALTER TABLE `unit_of_measures`
  ADD COLUMN IF NOT EXISTS `uom_code` VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `description` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `created_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME NULL DEFAULT NULL;

UPDATE `unit_of_measures`
SET `uom_code` = CONCAT('UOM-LEGACY-', LPAD(`id`, 4, '0'))
WHERE `uom_code` IS NULL
   OR `uom_code` = '';

ALTER TABLE `brands`
  ADD COLUMN IF NOT EXISTS `brand_code` VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `description` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `created_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME NULL DEFAULT NULL;

ALTER TABLE `models`
  ADD COLUMN IF NOT EXISTS `model_code` VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `description` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `created_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_by` INT(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME NULL DEFAULT NULL;

ALTER TABLE `property_thresholds`
  ADD COLUMN IF NOT EXISTS `basis` VARCHAR(255) DEFAULT NULL;

UPDATE `property_thresholds`
SET `basis` = COALESCE(`remarks`, 'COA Circular No. 2022-004')
WHERE `basis` IS NULL
   OR `basis` = '';

ALTER TABLE `receiving_item_details`
  ADD COLUMN IF NOT EXISTS `is_disposed` TINYINT(1) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS `audit_logs` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED DEFAULT NULL,
  `action` VARCHAR(100) DEFAULT NULL,
  `table_name` VARCHAR(100) DEFAULT NULL,
  `record_id` INT(10) UNSIGNED DEFAULT NULL,
  `old_values` LONGTEXT DEFAULT NULL,
  `new_values` LONGTEXT DEFAULT NULL,
  `module_name` VARCHAR(100) DEFAULT NULL,
  `record_type` VARCHAR(100) DEFAULT NULL,
  `action_name` VARCHAR(100) DEFAULT NULL,
  `description` LONGTEXT DEFAULT NULL,
  `ip_address` VARCHAR(50) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

INSERT INTO `audit_logs` (`id`, `user_id`, `action`, `table_name`, `record_id`, `description`, `ip_address`, `created_at`)
SELECT al.`id`, al.`user_id`, al.`action`, al.`module`, al.`reference_id`, al.`details`, al.`ip_address`, al.`created_at`
FROM `audit_log` al
WHERE NOT EXISTS (
  SELECT 1 FROM `audit_logs` x WHERE x.`id` = al.`id`
);
