USE `spamsdb`;

UPDATE `account_codes` SET `account_code` = '5.02.03.010.00', `account_name` = 'Office Supplies Expenses', `account_group` = 'supply' WHERE `account_code` = '5020301000';
UPDATE `account_codes` SET `account_code` = '5.02.03.020.00', `account_name` = 'Accountable Forms Expenses', `account_group` = 'supply' WHERE `account_code` = '5020302000';
UPDATE `account_codes` SET `account_code` = '5.02.03.090.00', `account_name` = 'Fuel, Oil and Lubricants Expenses', `account_group` = 'supply' WHERE `account_code` = '5020309000';
UPDATE `account_codes` SET `account_code` = '5.02.03.210.00', `account_name` = 'Semi-Expendable Machinery and Equipment Expenses', `account_group` = 'semi_expendable' WHERE `account_code` = '5020321000';
UPDATE `account_codes` SET `account_code` = '5.02.03.210.02', `account_name` = 'Semi-Expendable ME - Office Equipment', `account_group` = 'semi_expendable' WHERE `account_code` = '5020321002';
UPDATE `account_codes` SET `account_code` = '5.02.03.210.03', `account_name` = 'Semi-Expendable ME - Information & Communications Technology Equipment', `account_group` = 'semi_expendable' WHERE `account_code` = '5020321003';
UPDATE `account_codes` SET `account_code` = '5.02.03.210.07', `account_name` = 'Semi-Expendable ME - Communications Equipment', `account_group` = 'semi_expendable' WHERE `account_code` = '5020321007';
UPDATE `account_codes` SET `account_code` = '5.02.03.210.11', `account_name` = 'Semi-Expendable ME - Printing Equipment', `account_group` = 'semi_expendable' WHERE `account_code` = '5020321011';
UPDATE `account_codes` SET `account_code` = '5.02.03.210.99', `account_name` = 'Semi-Expendable ME - Other Machinery and Equipment', `account_group` = 'semi_expendable' WHERE `account_code` = '5020321099';
UPDATE `account_codes` SET `account_code` = '5.02.03.990.00', `account_name` = 'Other Supplies and Materials Expenses', `account_group` = 'supply' WHERE `account_code` = '5020399000';
UPDATE `account_codes` SET `account_code` = '1.06.05.010.00', `account_name` = 'Machinery', `account_group` = 'asset' WHERE `account_code` = '5060405000';
UPDATE `account_codes` SET `account_code` = '1.06.05.020.00', `account_name` = 'Office Equipment', `account_group` = 'asset' WHERE `account_code` = '5060405002';
UPDATE `account_codes` SET `account_code` = '1.06.05.030.00', `account_name` = 'Information and Communication Technology Equipment', `account_group` = 'asset' WHERE `account_code` = '5060405005';
UPDATE `account_codes` SET `account_code` = '1.06.05.070.00', `account_name` = 'Communication Equipment', `account_group` = 'asset' WHERE `account_code` = '5060405007';
UPDATE `account_codes` SET `account_code` = '1.06.05.120.00', `account_name` = 'Printing Equipment', `account_group` = 'asset' WHERE `account_code` = '5060405012';
UPDATE `account_codes` SET `account_code` = '1.06.05.990.00', `account_name` = 'Other Machinery and Equipment', `account_group` = 'asset' WHERE `account_code` = '5060405099';
UPDATE `account_codes` SET `account_code` = '1.06.07.010.00', `account_name` = 'Furniture and Fixtures', `account_group` = 'asset' WHERE `account_code` = '5060407001';
UPDATE `account_codes` SET `account_code` = '1.06.07.020.00', `account_name` = 'Books', `account_group` = 'asset' WHERE `account_code` = '5060407002';
UPDATE `account_codes` SET `account_code` = '1.06.99.990.00', `account_name` = 'Other Property, Plant and Equipment', `account_group` = 'asset' WHERE `account_code` = '5060409099';

INSERT INTO `account_codes` (`account_code`, `account_name`, `account_group`, `description`) VALUES
('1.06.01.010.00', 'Land', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.02.010.00', 'Land Improvements, Aquaculture Structures', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.02.020.00', 'Land Improvements, Reforestation Projects', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.02.990.00', 'Other Land Improvements', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.03.010.00', 'Road Networks', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.03.020.00', 'Flood Control Systems', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.03.030.00', 'Sewer Systems', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.03.040.00', 'Water Supply Systems', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.03.050.00', 'Power Supply Systems', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.03.060.00', 'Communication Networks', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.03.070.00', 'Seaport Systems', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.03.090.00', 'Parks, Plazas and Monuments', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.03.100.00', 'Other Infrastructure Assets', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.04.010.00', 'Buildings', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.04.020.00', 'School Buildings', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.04.030.00', 'Hospitals and Health Centers', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.04.040.00', 'Markets', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.04.050.00', 'Slaughterhouses', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.04.060.00', 'Hostels and Dormitories', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.04.990.00', 'Other Structures', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.05.040.00', 'Agricultural and Forestry Equipment', 'asset', 'COA/UACS seed from provided chart'),
('1.06.05.050.00', 'Marine and Fishery Equipment', 'asset', 'COA/UACS seed from provided chart'),
('1.06.05.060.00', 'Airport Equipment', 'asset', 'COA/UACS seed from provided chart'),
('1.06.05.080.00', 'Construction and Heavy Equipment', 'asset', 'COA/UACS seed from provided chart'),
('1.06.05.090.00', 'Disaster Response and Rescue Equipment', 'asset', 'COA/UACS seed from provided chart'),
('1.06.05.100.00', 'Military, Police and Security Equipment', 'asset', 'COA/UACS seed from provided chart'),
('1.06.05.110.00', 'Medical Equipment', 'asset', 'COA/UACS seed from provided chart'),
('1.06.05.130.00', 'Sports Equipment', 'asset', 'COA/UACS seed from provided chart'),
('1.06.05.140.00', 'Technical and Scientific Equipment', 'asset', 'COA/UACS seed from provided chart'),
('1.06.06.010.00', 'Motor Vehicles', 'asset', 'COA/UACS seed from provided chart'),
('1.06.06.990.00', 'Other Transportation Equipment', 'asset', 'COA/UACS seed from provided chart'),
('1.06.10.010.00', 'Construction in Progress - Land Improvements', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.10.020.00', 'Construction in Progress - Infrastructure Assets', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.10.030.00', 'Construction in Progress - Buildings and Other Structures', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.11.010.00', 'Historical Buildings', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.11.020.00', 'Works of Arts and Archeological Specimens', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.06.11.990.00', 'Other Heritage Assets', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.08.01.010.00', 'Patents/Copyrights', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.08.01.020.00', 'Computer Software', 'fixed_asset', 'COA/UACS seed from provided chart'),
('1.08.01.030.00', 'Other Intangible Assets', 'fixed_asset', 'COA/UACS seed from provided chart'),
('5.02.01.010.00', 'Travelling Expenses - Local', 'expense', 'COA/UACS seed from provided chart'),
('5.02.01.020.00', 'Travelling Expenses - Foreign', 'expense', 'COA/UACS seed from provided chart'),
('5.02.02.010.00', 'Training Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.02.020.00', 'Scholarship/Grants Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.03.030.00', 'Non-Accountable Forms Expenses', 'supply', 'COA/UACS seed from provided chart'),
('5.02.03.040.00', 'Animal/Zoological Supplies Expenses', 'supply', 'COA/UACS seed from provided chart'),
('5.02.03.050.00', 'Food Supplies Expenses', 'supply', 'COA/UACS seed from provided chart'),
('5.02.03.060.00', 'Welfare Goods Expenses', 'supply', 'COA/UACS seed from provided chart'),
('5.02.03.070.00', 'Drugs and Medicines Expenses', 'supply', 'COA/UACS seed from provided chart'),
('5.02.03.080.00', 'Medical, Dental and Laboratory Supplies Expenses', 'supply', 'COA/UACS seed from provided chart'),
('5.02.03.100.00', 'Agricultural and Marine Supplies Expenses', 'supply', 'COA/UACS seed from provided chart'),
('5.02.03.110.01', 'Textbooks and Instructional Materials Expenses', 'supply', 'COA/UACS seed from provided chart'),
('5.02.03.120.00', 'Military, Police and Traffic Supplies Expenses', 'supply', 'COA/UACS seed from provided chart'),
('5.02.03.130.00', 'Chemical and Filtering Supplies Expenses', 'supply', 'COA/UACS seed from provided chart'),
('5.02.03.210.01', 'Semi-Expendable ME - Machinery', 'semi_expendable', 'COA/UACS seed from provided chart'),
('5.02.03.210.04', 'Semi-Expendable ME - Agricultural and Forestry Equipment', 'semi_expendable', 'COA/UACS seed from provided chart'),
('5.02.03.210.05', 'Semi-Expendable ME - Marine and Fishery Equipment', 'semi_expendable', 'COA/UACS seed from provided chart'),
('5.02.03.210.08', 'Semi-Expendable ME - Disaster Response and Rescue Equipment', 'semi_expendable', 'COA/UACS seed from provided chart'),
('5.02.03.210.10', 'Semi-Expendable ME - Medical Equipment', 'semi_expendable', 'COA/UACS seed from provided chart'),
('5.02.03.210.12', 'Semi-Expendable ME - Sports Equipment', 'semi_expendable', 'COA/UACS seed from provided chart'),
('5.02.03.210.13', 'Semi-Expendable ME - Technical and Scientific Equipment', 'semi_expendable', 'COA/UACS seed from provided chart'),
('5.02.04.010.00', 'Water Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.04.020.00', 'Electricity Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.05.010.00', 'Postage and Courier Services', 'expense', 'COA/UACS seed from provided chart'),
('5.02.05.020.01', 'Telephone Expenses - Mobile', 'expense', 'COA/UACS seed from provided chart'),
('5.02.05.020.02', 'Telephone Expenses - Landline', 'expense', 'COA/UACS seed from provided chart'),
('5.02.05.030.00', 'Internet Subscription Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.05.040.00', 'Cable, Satellite, Telegraph and Radio Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.06.010.01', 'Awards/Rewards Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.06.010.02', 'Rewards and Incentives', 'expense', 'COA/UACS seed from provided chart'),
('5.02.06.020.00', 'Prizes', 'expense', 'COA/UACS seed from provided chart'),
('5.02.07.010.00', 'Survey Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.07.020.00', 'Research, Exploration and Development Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.08.010.00', 'Demolition and Relocation Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.08.020.00', 'Desilting and Dredging Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.09.010.00', 'Generation, Transmission and Distribution Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.10.010.00', 'Confidential Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.10.020.00', 'Intelligence Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.10.030.00', 'Extraordinary and Miscellaneous Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.11.010.00', 'Legal Services', 'expense', 'COA/UACS seed from provided chart'),
('5.02.11.020.00', 'Auditing Services', 'expense', 'COA/UACS seed from provided chart'),
('5.02.11.030.00', 'Consultancy Services', 'expense', 'COA/UACS seed from provided chart'),
('5.02.11.990.01', 'Other Professional Services - Part-time', 'expense', 'COA/UACS seed from provided chart'),
('5.02.11.990.02', 'Other Professional Services - Others', 'expense', 'COA/UACS seed from provided chart'),
('5.02.11.990.03', 'Other Professional Services - Summer', 'expense', 'COA/UACS seed from provided chart'),
('5.02.12.010.00', 'Environment/Sanitary Services', 'expense', 'COA/UACS seed from provided chart'),
('5.02.12.020.00', 'Janitorial Services', 'expense', 'COA/UACS seed from provided chart'),
('5.02.12.030.00', 'Security Services', 'expense', 'COA/UACS seed from provided chart'),
('5.02.12.990.00', 'Other General Services', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.010.00', 'Repairs and Maintenance - Investment Property', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.020.01', 'Repairs and Maintenance - Land Improvement - Aquaculture', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.020.02', 'Repairs and Maintenance - Land Improvement - Reforestation', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.020.99', 'Repairs and Maintenance - Land Improvement - Other Land Improvements', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.030.00', 'Repairs and Maintenance - Infrastructure Assets', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.040.01', 'Repairs and Maintenance - Buildings', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.040.02', 'Repairs and Maintenance - School Buildings', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.040.06', 'Repairs and Maintenance - Hostels and Dormitories', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.040.99', 'Repairs and Maintenance - Other Structures', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.050.01', 'Repairs and Maintenance - Machinery', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.050.02', 'Repairs and Maintenance - Office Equipment', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.050.03', 'Repairs and Maintenance - ICT Equipment', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.050.04', 'Repairs and Maintenance - Agricultural and Forestry Equipment', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.050.05', 'Repairs and Maintenance - Marine and Fishery Equipment', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.050.07', 'Repairs and Maintenance - Communication Equipment', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.050.10', 'Repairs and Maintenance - Military, Police and Security Equipment', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.050.11', 'Repairs and Maintenance - Medical Equipment', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.050.13', 'Repairs and Maintenance - Sports Equipment', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.050.14', 'Repairs and Maintenance - Technical and Scientific Equipment', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.050.99', 'Repairs and Maintenance - Other Machinery and Equipment', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.060.01', 'Repairs and Maintenance - Motor Vehicle', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.070.00', 'Repairs and Maintenance - Furniture and Fixtures', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.080.00', 'Repairs and Maintenance - Leased Assets', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.090.00', 'Repairs and Maintenance - Leased Assets Improvement', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.100.00', 'Repairs and Maintenance - Heritage Assets', 'expense', 'COA/UACS seed from provided chart'),
('5.02.13.990.99', 'Repairs and Maintenance - Other Property, Plant and Equipment', 'expense', 'COA/UACS seed from provided chart'),
('5.02.14.010.00', 'Subsidy to NGA''s', 'expense', 'COA/UACS seed from provided chart'),
('5.02.14.020.00', 'Financial Assistance to NGA''s', 'expense', 'COA/UACS seed from provided chart'),
('5.02.14.030.00', 'Financial Assistance to LGU''s', 'expense', 'COA/UACS seed from provided chart'),
('5.02.14.040.00', 'Budgetary Support to GOCC''s', 'expense', 'COA/UACS seed from provided chart'),
('5.02.14.050.00', 'Financial Assistance to NGO''s/PO''s', 'expense', 'COA/UACS seed from provided chart'),
('5.02.14.060.00', 'Internal Revenue Allotment', 'expense', 'COA/UACS seed from provided chart'),
('5.02.14.990.00', 'Subsidies - Others', 'expense', 'COA/UACS seed from provided chart'),
('5.02.15.010.00', 'Taxes, Duties and Licenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.15.020.00', 'Fidelity Bond Premiums', 'expense', 'COA/UACS seed from provided chart'),
('5.02.15.030.00', 'Insurance Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.16.010.00', 'Labor and Wages', 'expense', 'COA/UACS seed from provided chart'),
('5.02.99.010.00', 'Advertising Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.99.020.00', 'Printing and Publication Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.99.030.00', 'Representation Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.99.040.00', 'Transportation Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.99.050.00', 'Rent/Lease Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.99.060.00', 'Membership Dues and Contributions to Organizations', 'expense', 'COA/UACS seed from provided chart'),
('5.02.99.070.00', 'Subscription Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.99.080.00', 'Donations', 'expense', 'COA/UACS seed from provided chart'),
('5.02.99.090.00', 'Litigation/Acquired Assets Expenses', 'expense', 'COA/UACS seed from provided chart'),
('5.02.99.990.99', 'Other Maintenance and Operating Expenses', 'expense', 'COA/UACS seed from provided chart')
ON DUPLICATE KEY UPDATE
`account_name` = VALUES(`account_name`),
`account_group` = VALUES(`account_group`),
`description` = VALUES(`description`),
`updated_at` = NOW();
