USE `spamsdb`;

CREATE TABLE IF NOT EXISTS `asset_transfers` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `system_reference` VARCHAR(50) NOT NULL,
    `transfer_date` DATE NOT NULL,
    `source_type` ENUM('system','legacy') NOT NULL,
    `distribution_item_detail_id` BIGINT UNSIGNED NULL,
    `legacy_asset_id` BIGINT UNSIGNED NULL,
    `property_number` VARCHAR(100) NULL,
    `from_office_id` INT UNSIGNED NULL,
    `from_employee_id` INT UNSIGNED NULL,
    `from_responsibility_code_id` INT UNSIGNED NULL,
    `to_office_id` INT UNSIGNED NULL,
    `to_employee_id` INT UNSIGNED NULL,
    `to_responsibility_code_id` INT UNSIGNED NULL,
    `transfer_type` ENUM('donation','relocate','reassignment','others') NULL,
    `reason` TEXT NULL,
    `remarks` TEXT NULL,
    `status` ENUM('posted','cancelled') NOT NULL DEFAULT 'posted',
    `created_by` INT UNSIGNED NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY `uk_asset_transfers_system_reference` (`system_reference`),
    KEY `idx_asset_transfers_distribution_item_detail_id` (`distribution_item_detail_id`),
    KEY `idx_asset_transfers_legacy_asset_id` (`legacy_asset_id`),
    KEY `idx_asset_transfers_property_number` (`property_number`),
    KEY `idx_asset_transfers_from_office_id` (`from_office_id`),
    KEY `idx_asset_transfers_to_office_id` (`to_office_id`),
    KEY `idx_asset_transfers_created_by` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
