ALTER TABLE purchase_orders
    ADD COLUMN IF NOT EXISTS supplier_address TEXT NULL DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS place_of_delivery VARCHAR(200) NULL DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS delivery_term_days INT NULL DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS expected_delivery_date DATE NULL DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS mode_of_procurement_id BIGINT UNSIGNED NULL DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS purpose TEXT NULL DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS remarks TEXT NULL DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS updated_by BIGINT UNSIGNED NULL DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS updated_at DATETIME NULL DEFAULT NULL;