<?php
require_once __DIR__ . '/../../app/config/init.php'; require_login(); require_role('Administrator','Time Keeper'); header('Content-Type: application/json');
const DTR_DUPLICATE_WINDOW_SECONDS = 120;
$input=json_decode(file_get_contents('php://input'),true)?:[];
if(!hash_equals((string)csrf_token(),(string)($_SERVER['HTTP_X_CSRF_TOKEN']??''))){http_response_code(403);echo json_encode(['ok'=>false,'message'=>'Invalid CSRF token.']);exit;}
$db=db();$id=(int)($input['trainee_id']??0);$distance=(float)($input['match_distance']??0);
$stmt=$db?$db->prepare('SELECT id,first_name,last_name FROM dtr_trainees WHERE id=? AND is_active=1'):null;if(!$stmt){http_response_code(500);echo json_encode(['ok'=>false,'message'=>'Database unavailable.']);exit;}$stmt->bind_param('i',$id);$stmt->execute();$trainee=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$trainee){http_response_code(404);echo json_encode(['ok'=>false,'message'=>'Trainee not found.']);exit;}
$stmt=$db->prepare('SELECT log_type,logged_at FROM dtr_logs WHERE trainee_id=? ORDER BY logged_at DESC,id DESC LIMIT 1');$stmt->bind_param('i',$id);$stmt->execute();$recent=$stmt->get_result()->fetch_assoc();$stmt->close();if($recent&&(time()-strtotime($recent['logged_at']))<DTR_DUPLICATE_WINDOW_SECONDS){$label=$recent['log_type']==='time_in'?'in':'out';echo json_encode(['ok'=>true,'already_logged'=>true,'message'=>"You're already logged {$label} — recorded at ".date('g:i A',strtotime($recent['logged_at'])).'.']);exit;}
$stmt=$db->prepare('SELECT log_type FROM dtr_logs WHERE trainee_id=? AND DATE(logged_at)=CURDATE() ORDER BY logged_at DESC,id DESC LIMIT 1');$stmt->bind_param('i',$id);$stmt->execute();$today=$stmt->get_result()->fetch_assoc();$stmt->close();$type=(!$today||$today['log_type']==='time_out')?'time_in':'time_out';$source='face_kiosk';$stmt=$db->prepare('INSERT INTO dtr_logs (trainee_id,log_type,match_distance,source) VALUES (?,?,?,?)');$stmt->bind_param('isds',$id,$type,$distance,$source);$ok=$stmt->execute();$stmt->close();$name=trim($trainee['first_name'].' '.$trainee['last_name']);echo json_encode(['ok'=>$ok,'already_logged'=>false,'message'=>($type==='time_in'?'Welcome, ':'Goodbye, ').$name.' — '.($type==='time_in'?'Time In ':'Time Out ').date('g:i A')]);
