<?php
require_once __DIR__ . '/../../app/config/init.php';
require_login();
require_role('Administrator', 'Time Keeper');
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DTR Kiosk</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<style>
html,body{height:100%;margin:0;background:#101827;color:#fff}.kiosk{min-height:100vh;display:flex;flex-direction:column;padding:1.25rem}.kiosk-top{width:min(100%,1100px);margin:0 auto 1rem;display:flex;justify-content:space-between;gap:1rem;align-items:center}.kiosk-stage{position:relative;flex:1;min-height:0;width:min(100%,1100px);margin:auto;border:1px solid #334155;border-radius:1.25rem;overflow:hidden;background:#000;box-shadow:0 20px 50px #0008}.feed{width:100%;height:100%;object-fit:contain;background:#000}.status{position:absolute;z-index:2;bottom:8%;left:50%;transform:translateX(-50%);width:min(88%,780px);font-size:clamp(1.15rem,2vw,1.85rem);font-weight:600;text-align:center;background:#101827dc;border-radius:1rem;padding:.9rem 1rem}.scan{position:absolute;z-index:2;bottom:2%;left:50%;transform:translateX(-50%);font-size:.85rem;color:#d5deeb}.dot{display:inline-block;width:.55rem;height:.55rem;border-radius:50%;background:#6ee7b7;animation:pulse 1.5s infinite}@keyframes pulse{50%{opacity:.25}}@media(max-width:700px){.kiosk{padding:.75rem}.kiosk-top{align-items:flex-start;flex-direction:column}.kiosk-top .fs-3{font-size:1.35rem!important}.kiosk-stage{min-height:60vh;border-radius:.85rem}}
</style></head><body><main class="kiosk"><header class="kiosk-top"><strong class="fs-3">OJT Daily Time Record</strong><div class="d-flex flex-wrap gap-2"><select class="form-select form-select-sm" id="cameraSelect" aria-label="Select camera" disabled><option>Loading cameras...</option></select><button class="btn btn-outline-light btn-sm" type="button" id="refreshCameras">Refresh cameras</button><button class="btn btn-outline-light" onclick="window.open(location.href,'dtrKiosk','width=1100,height=800')">New Window</button><button class="btn btn-light" id="full">Fullscreen</button><a class="btn btn-link text-light" href="<?php echo h(base_url('auth/logout.php')); ?>">Log out</a></div></header><div class="kiosk-stage"><video id="video" class="feed" autoplay muted playsinline></video><div id="status" class="status">Loading face recognition models from SPAMS...</div><div id="scanning" class="scan"><span class="dot"></span> Scanning every 5 seconds</div></div></main>
<script src="https://cdn.jsdelivr.net/npm/face-api.js@0.22.2/dist/face-api.min.js"></script><script>
const FACE_MATCH_THRESHOLD=.6,SCAN_INTERVAL_MS=5000,video=document.getElementById('video'),status=document.getElementById('status'),scanning=document.getElementById('scanning'),cameraSelect=document.getElementById('cameraSelect'),refreshCameras=document.getElementById('refreshCameras');let enrolled=[],busy=false,cameraStream=null;
function message(text,kind){status.textContent=text;status.className='status '+(kind||'');}
function stopCamera(){if(cameraStream)cameraStream.getTracks().forEach(track=>track.stop());cameraStream=null;}
async function loadCameras(selectedId=''){const devices=await navigator.mediaDevices.enumerateDevices();const cameras=devices.filter(device=>device.kind==='videoinput');cameraSelect.innerHTML='';cameras.forEach((camera,index)=>{const option=document.createElement('option');option.value=camera.deviceId;option.textContent=camera.label||'Camera '+(index+1);cameraSelect.appendChild(option);});cameraSelect.disabled=!cameras.length;if(selectedId&&cameras.some(camera=>camera.deviceId===selectedId))cameraSelect.value=selectedId;}
async function startCamera(deviceId=''){stopCamera();const videoConstraints=deviceId?{deviceId:{exact:deviceId}}:{facingMode:'user'};cameraStream=await navigator.mediaDevices.getUserMedia({video:videoConstraints,audio:false});video.srcObject=cameraStream;await loadCameras(cameraStream.getVideoTracks()[0]?.getSettings().deviceId||deviceId);}
async function boot(){const base='<?php echo h(base_url('assets/vendor/face-api/models')); ?>';try{await Promise.all([faceapi.nets.tinyFaceDetector.loadFromUri(base),faceapi.nets.faceLandmark68Net.loadFromUri(base),faceapi.nets.faceRecognitionNet.loadFromUri(base)]);}catch(e){console.error('DTR model load failed:',e);message('Face models could not be loaded from the SPAMS server. No installation is needed on this PC; check the server connection.','text-warning');return;}try{const descriptorResponse=await fetch('dtr_descriptors.php');if(!descriptorResponse.ok)throw new Error('Unable to load enrolled trainees.');enrolled=await descriptorResponse.json();await startCamera();message('Ready - look at the camera to clock in or out.');setTimeout(scan,1000);setInterval(scan,SCAN_INTERVAL_MS);}catch(e){console.error('DTR kiosk camera/setup failed:',e);message(window.isSecureContext?'Camera access was blocked. Allow camera permission in this browser.':'Camera access on another PC requires HTTPS. Open SPAMS using its HTTPS address, then allow camera access.','text-warning');}}
async function scan(){if(busy||!video.videoWidth||!enrolled.length)return;scanning.textContent='Scanning...';const detection=await faceapi.detectSingleFace(video,new faceapi.TinyFaceDetectorOptions()).withFaceLandmarks().withFaceDescriptor();scanning.innerHTML='<span class="dot"></span> Scanning every 5 seconds';if(!detection){message('Face not recognized');return;}let best=null;enrolled.forEach(t=>{const distance=faceapi.euclideanDistance(detection.descriptor,new Float32Array(t.descriptor));if(!best||distance<best.distance)best={...t,distance};});if(!best||best.distance>=FACE_MATCH_THRESHOLD){message('Face not recognized');return;}busy=true;const response=await fetch('dtr_log.php',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':'<?php echo h(csrf_token()); ?>'},body:JSON.stringify({trainee_id:best.trainee_id,match_distance:best.distance})});const out=await response.json();message(out.message||'Unable to save time log.',out.already_logged?'text-warning':'text-success');setTimeout(()=>{message('Ready - look at the camera to clock in or out.');busy=false;},5000);}
cameraSelect.addEventListener('change',async()=>{try{message('Switching camera...');await startCamera(cameraSelect.value);message('Ready - look at the camera to clock in or out.');}catch(e){console.error('DTR camera switch failed:',e);message('Unable to switch camera. Allow camera access and try again.','text-warning');}});refreshCameras.addEventListener('click',async()=>{try{await loadCameras(cameraSelect.value);}catch(e){console.error('DTR camera refresh failed:',e);message('Unable to list cameras. Allow camera access first.','text-warning');}});window.addEventListener('beforeunload',stopCamera);document.getElementById('full').onclick=()=>document.documentElement.requestFullscreen();boot();
</script></body></html>
