<?php
require_once __DIR__ . '/../../app/config/init.php';
require_login();
require_role('Administrator', 'Time Keeper');
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DTR Kiosk</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<style>
html,body{height:100%;margin:0;background:#101827;color:#fff}.kiosk{min-height:100vh;display:flex;flex-direction:column;padding:1.25rem}.kiosk-top{width:min(100%,1100px);margin:0 auto 1rem;display:flex;justify-content:space-between;gap:1rem;align-items:center}.kiosk-stage{position:relative;flex:1;min-height:0;width:min(100%,1100px);margin:auto;border:1px solid #334155;border-radius:1.25rem;overflow:hidden;background:#000;box-shadow:0 20px 50px #0008}.feed{width:100%;height:100%;object-fit:contain;background:#000}.status{position:absolute;z-index:2;bottom:8%;left:50%;transform:translateX(-50%);width:min(88%,780px);font-size:clamp(1.15rem,2vw,1.85rem);font-weight:600;text-align:center;background:#101827dc;border-radius:1rem;padding:.9rem 1rem}.scan{position:absolute;z-index:2;bottom:2%;left:50%;transform:translateX(-50%);font-size:.85rem;color:#d5deeb}.dot{display:inline-block;width:.55rem;height:.55rem;border-radius:50%;background:#6ee7b7;animation:pulse 1.5s infinite}@keyframes pulse{50%{opacity:.25}}@media(max-width:700px){.kiosk{padding:.75rem}.kiosk-top{align-items:flex-start;flex-direction:column}.kiosk-top .fs-3{font-size:1.35rem!important}.kiosk-stage{min-height:60vh;border-radius:.85rem}}
</style></head><body><main class="kiosk"><header class="kiosk-top"><strong class="fs-3">OJT Daily Time Record</strong><div class="d-flex flex-wrap gap-2"><button class="btn btn-outline-light" onclick="window.open(location.href,'dtrKiosk','width=1100,height=800')">New Window</button><button class="btn btn-light" id="full">Fullscreen</button><a class="btn btn-link text-light" href="<?php echo h(base_url('auth/logout.php')); ?>">Log out</a></div></header><div class="kiosk-stage"><video id="video" class="feed" autoplay muted playsinline></video><div id="status" class="status">Loading local face recognition models…</div><div id="scanning" class="scan"><span class="dot"></span> Scanning every 5 seconds</div></div></main>
<script src="https://cdn.jsdelivr.net/npm/face-api.js@0.22.2/dist/face-api.min.js"></script><script>
const FACE_MATCH_THRESHOLD=.6,SCAN_INTERVAL_MS=5000,video=document.getElementById('video'),status=document.getElementById('status'),scanning=document.getElementById('scanning');let enrolled=[],busy=false;
function message(text,kind){status.textContent=text;status.className='status '+(kind||'');}
async function boot(){try{const base='<?php echo h(base_url('assets/vendor/face-api/models')); ?>';await Promise.all([faceapi.nets.tinyFaceDetector.loadFromUri(base),faceapi.nets.faceLandmark68Net.loadFromUri(base),faceapi.nets.faceRecognitionNet.loadFromUri(base)]);enrolled=await(await fetch('dtr_descriptors.php')).json();video.srcObject=await navigator.mediaDevices.getUserMedia({video:true});message('Ready — look at the camera to clock in or out.');setTimeout(scan,1000);setInterval(scan,SCAN_INTERVAL_MS);}catch(e){message('Camera or face models unavailable. Allow camera access and install local model files.','text-warning');}}
async function scan(){if(busy||!video.videoWidth||!enrolled.length)return;scanning.textContent='Scanning…';const detection=await faceapi.detectSingleFace(video,new faceapi.TinyFaceDetectorOptions()).withFaceLandmarks().withFaceDescriptor();scanning.innerHTML='<span class="dot"></span> Scanning every 5 seconds';if(!detection){message('Face not recognized');return;}let best=null;enrolled.forEach(t=>{const distance=faceapi.euclideanDistance(detection.descriptor,new Float32Array(t.descriptor));if(!best||distance<best.distance)best={...t,distance};});if(!best||best.distance>=FACE_MATCH_THRESHOLD){message('Face not recognized');return;}busy=true;const response=await fetch('dtr_log.php',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':'<?php echo h(csrf_token()); ?>'},body:JSON.stringify({trainee_id:best.trainee_id,match_distance:best.distance})});const out=await response.json();message(out.message||'Unable to save time log.',out.already_logged?'text-warning':'text-success');setTimeout(()=>{message('Ready — look at the camera to clock in or out.');busy=false;},5000);}
document.getElementById('full').onclick=()=>document.documentElement.requestFullscreen();boot();
</script></body></html>
