<?php
require_once __DIR__ . '/../../app/config/init.php';
require_login();
require_role('Administrator', 'Time Keeper');

$page_title = 'OJT Trainees';
$db = db();
$errors = [];
$flash = get_flash();
$editId = (int) ($_GET['edit_id'] ?? 0);
$form = ['id' => '', 'first_name' => '', 'middle_name' => '', 'last_name' => '', 'course' => '', 'year_level' => '', 'address' => '', 'contact_number' => '', 'email' => '', 'face_descriptor' => '', 'is_active' => 1];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!csrf_verify()) {
        $errors[] = 'Invalid CSRF token.';
    } else {
        $action = trim((string) ($_POST['action'] ?? 'save'));
        $form = [
            'id' => (int) ($_POST['id'] ?? 0), 'first_name' => trim((string) ($_POST['first_name'] ?? '')),
            'middle_name' => trim((string) ($_POST['middle_name'] ?? '')), 'last_name' => trim((string) ($_POST['last_name'] ?? '')),
            'course' => trim((string) ($_POST['course'] ?? '')), 'year_level' => trim((string) ($_POST['year_level'] ?? '')),
            'address' => trim((string) ($_POST['address'] ?? '')), 'contact_number' => trim((string) ($_POST['contact_number'] ?? '')),
            'email' => trim((string) ($_POST['email'] ?? '')), 'face_descriptor' => trim((string) ($_POST['face_descriptor'] ?? '')), 'is_active' => isset($_POST['is_active']) ? 1 : 0,
        ];
        if ($action === 'toggle') {
            $id = (int) ($_POST['id'] ?? 0); $active = (int) ($_POST['is_active'] ?? 0); $userId = current_user_id();
            $stmt = $db ? $db->prepare('UPDATE dtr_trainees SET is_active = ?, updated_by = ? WHERE id = ?') : null;
            if ($stmt) { $stmt->bind_param('iii', $active, $userId, $id); $stmt->execute(); $stmt->close(); set_flash('success', $active ? 'Trainee activated.' : 'Trainee deactivated.'); redirect('modules/dtr/trainees.php'); }
            $errors[] = 'Unable to update trainee status.';
        } elseif ($form['first_name'] === '' || $form['last_name'] === '') {
            $errors[] = 'First name and last name are required.';
        } elseif (!is_array(json_decode($form['face_descriptor'], true)) || count(json_decode($form['face_descriptor'], true)) !== 128) {
            $errors[] = 'Capture all three face shots before saving the trainee.';
        } elseif ($db) {
            $userId = current_user_id();
            if ((int) $form['id'] > 0) {
                $stmt = $db->prepare('UPDATE dtr_trainees SET first_name=?, middle_name=NULLIF(?, \'\'), last_name=?, course=NULLIF(?, \'\'), year_level=NULLIF(?, \'\'), address=NULLIF(?, \'\'), contact_number=NULLIF(?, \'\'), email=NULLIF(?, \'\'), face_descriptor=?, is_active=?, updated_by=? WHERE id=?');
                $stmt->bind_param('sssssssssiii', $form['first_name'], $form['middle_name'], $form['last_name'], $form['course'], $form['year_level'], $form['address'], $form['contact_number'], $form['email'], $form['face_descriptor'], $form['is_active'], $userId, $form['id']);
            } else {
                $stmt = $db->prepare('INSERT INTO dtr_trainees (first_name,middle_name,last_name,course,year_level,address,contact_number,email,face_descriptor,is_active,created_by) VALUES (?,NULLIF(?, \'\'),?,NULLIF(?, \'\'),NULLIF(?, \'\'),NULLIF(?, \'\'),NULLIF(?, \'\'),NULLIF(?, \'\'),?, ?,?)');
                $stmt->bind_param('sssssssssii', $form['first_name'], $form['middle_name'], $form['last_name'], $form['course'], $form['year_level'], $form['address'], $form['contact_number'], $form['email'], $form['face_descriptor'], $form['is_active'], $userId);
            }
            if ($stmt && $stmt->execute()) { $stmt->close(); set_flash('success', (int) $form['id'] ? 'Trainee updated.' : 'Trainee added.'); redirect('modules/dtr/trainees.php'); }
            $errors[] = 'Unable to save trainee.';
        }
    }
}
if ($editId > 0 && $db) { $stmt = $db->prepare('SELECT * FROM dtr_trainees WHERE id=?'); $stmt->bind_param('i', $editId); $stmt->execute(); $form = $stmt->get_result()->fetch_assoc() ?: $form; $stmt->close(); }
$trainees = [];
if ($db) { $res = $db->query("SELECT id, first_name, middle_name, last_name, course, year_level, contact_number, email, is_active, face_descriptor IS NOT NULL AS face_enrolled FROM dtr_trainees ORDER BY is_active DESC, last_name, first_name"); if ($res) $trainees = $res->fetch_all(MYSQLI_ASSOC); }
require_once __DIR__ . '/../../includes/header.php'; require_once __DIR__ . '/../../includes/sidebar.php'; require_once __DIR__ . '/../../includes/topbar.php';
?>
<section class="row g-4 page-section"><div class="col-lg-4"><div class="card"><div class="card-body p-4"><h5 class="page-title mb-1"><?php echo (int) ($form['id'] ?? 0) ? 'Edit trainee' : 'Add trainee'; ?></h5><p class="text-muted small">OJT records are separate from employee records.</p>
<?php foreach ($errors as $error): ?><div class="alert alert-danger small"><?php echo h($error); ?></div><?php endforeach; ?>
<form method="post" class="row g-3"><input type="hidden" name="_csrf" value="<?php echo h(csrf_token()); ?>"><input type="hidden" name="id" value="<?php echo (int) ($form['id'] ?? 0); ?>">
<div class="col-md-6"><label class="form-label">First Name *</label><input class="form-control" name="first_name" required value="<?php echo h($form['first_name'] ?? ''); ?>"></div><div class="col-md-6"><label class="form-label">Last Name *</label><input class="form-control" name="last_name" required value="<?php echo h($form['last_name'] ?? ''); ?>"></div><div class="col-12"><label class="form-label">Middle Name</label><input class="form-control" name="middle_name" value="<?php echo h($form['middle_name'] ?? ''); ?>"></div><div class="col-md-6"><label class="form-label">Course</label><input class="form-control" name="course" value="<?php echo h($form['course'] ?? ''); ?>"></div><div class="col-md-6"><label class="form-label">Year Level</label><input class="form-control" name="year_level" value="<?php echo h($form['year_level'] ?? ''); ?>"></div><div class="col-12"><label class="form-label">Address</label><input class="form-control" name="address" value="<?php echo h($form['address'] ?? ''); ?>"></div><div class="col-md-6"><label class="form-label">Contact Number</label><input class="form-control" name="contact_number" value="<?php echo h($form['contact_number'] ?? ''); ?>"></div><div class="col-md-6"><label class="form-label">Email</label><input type="email" class="form-control" name="email" value="<?php echo h($form['email'] ?? ''); ?>"></div>
<div class="col-12"><input type="hidden" name="face_descriptor" id="faceDescriptor"><div class="border rounded-3 p-3 bg-light-subtle"><div class="d-flex justify-content-between align-items-center gap-2"><div><div class="fw-semibold">Face capture — 3 shots required</div><div class="small text-muted" id="faceCapturePrompt">Start the camera, then capture Shot 1 of 3.</div></div><button type="button" class="btn btn-sm btn-outline-primary" id="startCamera">Start Camera</button></div><video id="faceVideo" class="w-100 rounded bg-dark mt-3 d-none" autoplay muted playsinline></video><div class="row g-2 mt-2" id="faceShotStatus"><div class="col-4"><div class="border rounded p-2 small" data-shot="0">Shot 1: waiting</div></div><div class="col-4"><div class="border rounded p-2 small" data-shot="1">Shot 2: waiting</div></div><div class="col-4"><div class="border rounded p-2 small" data-shot="2">Shot 3: waiting</div></div></div><div class="mt-3 d-flex gap-2"><button type="button" class="btn btn-primary" id="captureFace" disabled>Capture Shot 1</button><button type="button" class="btn btn-outline-secondary d-none" id="restartFace">Start over</button></div></div></div>
<div class="col-12 form-check ms-2"><input class="form-check-input" type="checkbox" name="is_active" id="active" value="1" <?php echo !empty($form['is_active']) ? 'checked' : ''; ?>><label class="form-check-label" for="active">Active</label></div><div class="col-12 d-flex gap-2"><button class="btn btn-primary" id="saveTrainee" disabled>Save Trainee</button><?php if ($editId): ?><a class="btn btn-outline-secondary" href="trainees.php">Cancel</a><?php endif; ?></div></form></div></div></div>
<div class="col-lg-8"><div class="card"><div class="card-body p-4"><div class="workspace-header mb-3"><div class="workspace-header-copy"><h5 class="page-title mb-1">OJT Trainees</h5><p class="text-muted mb-0">Enroll a face before using the kiosk.</p></div><div class="workspace-actions"><a href="kiosk.php" class="btn btn-outline-primary">Open Kiosk</a></div></div><?php if ($flash): ?><div class="alert alert-success"><?php echo h($flash['message']); ?></div><?php endif; ?><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Name</th><th>Course</th><th>Year</th><th>Contact</th><th>Face</th><th>Status</th><th></th></tr></thead><tbody><?php foreach ($trainees as $trainee): ?><tr><td class="fw-semibold"><?php echo h(trim($trainee['last_name'].', '.$trainee['first_name'].' '.$trainee['middle_name'])); ?></td><td><?php echo h($trainee['course'] ?? ''); ?></td><td><?php echo h($trainee['year_level'] ?? ''); ?></td><td><?php echo h($trainee['contact_number'] ?? ''); ?></td><td><span class="badge <?php echo $trainee['face_enrolled'] ? 'text-bg-success' : 'text-bg-secondary'; ?>"><?php echo $trainee['face_enrolled'] ? 'Face enrolled' : 'Not enrolled'; ?></span></td><td><span class="badge <?php echo $trainee['is_active'] ? 'text-bg-primary' : 'text-bg-secondary'; ?>"><?php echo $trainee['is_active'] ? 'Active' : 'Inactive'; ?></span></td><td class="text-end"><a class="btn btn-sm btn-outline-secondary" href="trainees.php?edit_id=<?php echo (int) $trainee['id']; ?>">Edit</a><a class="btn btn-sm btn-outline-primary" href="enroll.php?trainee_id=<?php echo (int) $trainee['id']; ?>">Enroll Face</a><form method="post" class="d-inline"><input type="hidden" name="_csrf" value="<?php echo h(csrf_token()); ?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?php echo (int) $trainee['id']; ?>"><input type="hidden" name="is_active" value="<?php echo $trainee['is_active'] ? 0 : 1; ?>"><button class="btn btn-sm btn-link"><?php echo $trainee['is_active'] ? 'Deactivate' : 'Activate'; ?></button></form></td></tr><?php endforeach; ?><?php if (!$trainees): ?><tr><td colspan="7" class="text-center text-muted py-4">No trainees recorded yet.</td></tr><?php endif; ?></tbody></table></div></div></div></div></section>
<script src="https://cdn.jsdelivr.net/npm/face-api.js@0.22.2/dist/face-api.min.js"></script><script>document.addEventListener('DOMContentLoaded',function(){const v=document.getElementById('faceVideo'),start=document.getElementById('startCamera'),cap=document.getElementById('captureFace'),reset=document.getElementById('restartFace'),prompt=document.getElementById('faceCapturePrompt'),hidden=document.getElementById('faceDescriptor'),save=document.getElementById('saveTrainee');let shots=[],ready=false;function update(){document.querySelectorAll('#faceShotStatus [data-shot]').forEach((el,i)=>{el.textContent='Shot '+(i+1)+': '+(shots[i]?'captured ✓':'waiting');el.classList.toggle('border-success',!!shots[i]);});if(shots.length===3){hidden.value=JSON.stringify(shots[0].map((_,i)=>(shots[0][i]+shots[1][i]+shots[2][i])/3));prompt.textContent='Face captured ✓ (3 shots averaged) — ready to save.';cap.disabled=true;save.disabled=false;reset.classList.remove('d-none');}else cap.textContent='Capture Shot '+(shots.length+1);}start.addEventListener('click',async()=>{try{const b='<?php echo h(base_url('assets/vendor/face-api/models'));?>';await Promise.all([faceapi.nets.tinyFaceDetector.loadFromUri(b),faceapi.nets.faceLandmark68Net.loadFromUri(b),faceapi.nets.faceRecognitionNet.loadFromUri(b)]);v.srcObject=await navigator.mediaDevices.getUserMedia({video:true});v.classList.remove('d-none');ready=true;cap.disabled=false;prompt.textContent='Camera ready. Capture Shot 1 of 3.';}catch(e){prompt.textContent='Camera or local face models unavailable. Allow camera access and check model files.';}});cap.addEventListener('click',async()=>{cap.disabled=true;const n=shots.length+1;prompt.textContent='Detecting Shot '+n+'…';const d=await faceapi.detectSingleFace(v,new faceapi.TinyFaceDetectorOptions()).withFaceLandmarks().withFaceDescriptor();if(!d){prompt.textContent='No clear face detected for Shot '+n+'. Adjust position then retry.';document.querySelector('[data-shot="'+shots.length+'"]').textContent='Shot '+n+': retry';cap.disabled=false;return;}shots.push(Array.from(d.descriptor));prompt.textContent=shots.length<3?'Shot '+n+' of 3 captured ✓ — ask trainee to tilt slightly, then capture again.':'';cap.disabled=shots.length===3;update();});reset.addEventListener('click',()=>{shots=[];hidden.value='';save.disabled=true;cap.disabled=!ready;reset.classList.add('d-none');prompt.textContent='Start over: capture Shot 1 of 3.';update();});update();});</script>
<?php require_once __DIR__ . '/../../includes/footer.php'; ?>
